#! /bin/sh
for i in {1..100}
do
    lein run 200 200 :simple :lexicase-selection true :uniform-crossover true 0.09 0.1 true false true
    lein run 200 200 :simple :tournament-selection true :uniform-crossover true 0.09 0.1 true false true
    lein run 200 200 :simple :lexicase-selection true :single-point-crossover true 0.09 0.1 true false true
    lein run 200 200 :simple :lexicase-selection true :uniform-crossover true 0.15 0.1 true false true
    lein run 200 200 :simple :lexicase-selection true :uniform-crossover true 0.2 0.2 true false true
done
